### PR TITLE
docs: Add personas, use cases, user stories, and requirements

### PR DESCRIPTION
**Pull request by simonsan**
For future use, I generated some Personas with ChatGPT4. I then created use cases and user stories out of it and collected some requirements. The requirements are probably not all something for us. Most of them, though, are.

Depends on #830.

### CODE REVIEW

**Comment by coopbri** [comment]
> Moved it into https://rustic.cli.rs/docs/design/analysis/intro.html because I think it fits much better than into the code repository.

Hey there, noticed this is a dead link now, just a heads up. I know this project is turbulent so things are changing rapidly. On a related note, super cool seeing this project evolve, talk about a bright future! I noticed the website and repo are quite different from even a month ago.

Also, wondering if you are looking for developers to help build out the UI client. I did see you discussed this with another community member in August on Discord [here](https://discord.com/channels/1101748142694748181/1101748180007264276/1141225201699397652) (Tauri + Svelte). I was thinking of implementing a Rustic frontend in Tauri + React or Tauri + Leptos.

**Comment by aawsome** [comment]
@coopbri Thanks for your feedback - yes we are changing things currently and running a bit out of time atm to finish things, unfortunately - hope this will improve in the next weeks/months.

If you are interested in making a UI, please don't hesitate to start! rustic_core is ready and should have almost all features needed for a UI - if something is missing, don't hesitate to ask!
I think we rustic developers miss time currently to actively work on a UI.

See also https://github.com/emuell/restic-browser/issues/75 - maybe you can work on a joined project! Note that there is already the (reserved) crate rustic_gui. If you like to be this the name on the UI you are working, we would like to host this under github.com/rustic-rs/. But you can of course also make your own project!

**Comment by coopbri** [comment]
Hey, this is FOSS, your efforts are much appreciated, believe me. Totally understand the time sink.

That's great! I didn't catch that recent discussion, thanks for sharing that. I'll catch up on the state of things and plan from there. Cheers!

**Comment by coopbri** [comment]
For sure! @coopbri on Discord :)

**Pull request closed without merging**
