### PR TITLE
Enable building on OpenBSD

### PR DESCRIPTION
**Pull request by bket**
This is needed to get rustic to build on OpenBSD. Lightly run tested the build against a local restic repo.

### CODE REVIEW

**Review by klemensn — APPROVED** [review]

**Comment by aawsome** [comment]
Hi @bket 
Thank you very much for the PR! Would you mind adding OpenBSD targets in the CI/CD pipeline? 
Then builds are tested for OpenBSD and binaries are automatically released
`.github/workflows/release.yaml` is the right  place, I think we should add `x86_64-unknown-freebsd` or `x86_64-unknown-netbsd` as target - which is the right one?

**Comment by bket** [comment]
> I think we should add `x86_64-unknown-freebsd` or `x86_64-unknown-netbsd` as target - which is the right one?

If I understand [https://doc.rust-lang.org/rustc/platform-support/openbsd.html](https://doc.rust-lang.org/rustc/platform-support/openbsd.html) correctly the target name should read $ARCH-unknown-openbsd, where $ARCH specifies the target processor architecture. I am not familiar with setting up a pipeline, so chances are that I missed something. For now I only added `x86_64-unknown-openbsd` as a target.

**Comment by aawsome** [comment]
Ok, just realized that the release build pipeline doesn't run for "external" PRs. I'll just give it a try ;-)

**Review by aawsome — APPROVED** [review]
LGTM! I'm also not sure if the CI runs, but let's try it out!

**Comment by aawsome** [comment]
Seems the toolchain support is missing to successfully.
I tried openbsd, netbsd and freebsd. #407 should add compile support for freebsd but binary builds were only possible for netbsd. For openbsd, there seems issues like https://github.com/rust-lang/rustup/issues/2168 which prevent the cross-compiling.

**Pull request merged**
