### PR TITLE
archiver: rework implementation

### PR DESCRIPTION
**Pull request by aawsome**

### CODE REVIEW

**Comment by aawsome** [comment]
@Dr-Emann Do you plan to review this? If not, I'll make a review myself as I'm willing to merge this soon...

**Comment by Dr-Emann** [comment]
I don't know that I'll have a chance to review, unfortunately, sorry.

**Comment by aawsome** [comment]
> I don't know that I'll have a chance to review, unfortunately, sorry.

No worries. I know it's a big change, but I think it's worth as it will make the archiver steps more clear and will allow you to implement something like #395 on top. In general, it allows to decouple the backup source from the archiving process...

**Comment by aawsome** [comment]
rebased.

**Comment by aawsome** [comment]
I did a review and some simplifications of the complicated types. Now IMO this is mergeable :-)
As a side note - I just saw some errors processing trees on windows and have the good hope that this PR will also salvage these. But that will need some more testing... for Windows topics, see #487

**Pull request merged**
