### PR TITLE
Use `unix` metadata extensions, rather than linux-specific ones

### PR DESCRIPTION
**Pull request by Dr-Emann**
This at least makes it compile, and pass what tests there are on my macbook.

### CODE REVIEW

**Comment by aawsome** [comment]
So far there are not many tests, unfortunately.
I myself only have linux machines at hand to run tests but I'm very excited to get rustic working on other OSes, too.

Did you try a sequence of `rustic-rs init`, `rust-rs backup` with you branch on a macbook and took a look at some saved trees? 

Cating saved trees can be done by `rustic-rs cat tree <SNAPSHOT-ID> <PATH>`
where `SNAPSHOT-ID` can be the (unique) start of an id, like a1bc5f or even `latest`.
In my example I would e.g. run `rustic-rs -r /tmp/repo cat tree latest /home/alex-dev/rust/rustic-rs/src/commands`

**Comment by Dr-Emann** [comment]
It looks like it works to me, yep

**Comment by aawsome** [comment]
@Dr-Emann: Thanks a lot for proposing this PR!

I manually checked that this PR also doesn't change anything on linux.
So, looks good to me!

Which targets are relevant for supporting macbooks? Are these two sufficient?
aarch64-apple-darwin
x86_64-apple-darwin

**Review by aawsome — APPROVED** [review]
LGTM

**Comment by aawsome** [comment]
I also added tests on MacOS on the CI pipeline, see #8

**Pull request merged**
